%% Design anti-aliasing filter
AAFilt_3000_3200 = designfilt('lowpassfir', ...
    'PassbandFrequency', 3000, ...
    'StopbandFrequency', 3200, ...
    'PassbandRipple', 0.0000001, ...
    'StopbandAttenuation', 65, ...
    'DesignMethod', 'equiripple', ...
    'SampleRate', 48000);
fvtool(AAFilt_3000_3200)
saveas(gcf, 'S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\AAFilt_3000_3200.png')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\AAFilt_3000_3200.mat', 'AAFilt_3000_3200')


%% Design low-pass filters
LPFilt_110_119_6kHz = designfilt('lowpassfir', ...
    'PassbandFrequency', 110, ...       % was 185 before
    'StopbandFrequency', 119, ...
    'PassbandRipple', 0.0001, ...
    'StopbandAttenuation', 65, ...
    'DesignMethod', 'equiripple', ...
    'SampleRate', 6000);
fvtool(LPFilt_110_119_6kHz)
saveas(gcf, 'S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\LPFilt_110_119_6kHz.png')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\LPFilt_110_119_6kHz.mat', 'LPFilt_110_119_6kHz')

LPFilt_110_119_48kz = designfilt('lowpassfir', ...
    'PassbandFrequency', 110, ...       % was 185 before
    'StopbandFrequency', 119, ...
    'PassbandRipple', 0.0001, ...
    'StopbandAttenuation', 65, ...
    'DesignMethod', 'equiripple', ...
    'SampleRate', 48000);
fvtool(LPFilt_110_119_48kHz)
saveas(gcf, 'S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\LPFilt_110_119_48kHz.png')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\LPFilt_110_119_48kHz.mat', 'LPFilt_110_119_48kHz')


LPFilt_50_59 = designfilt('lowpassfir', ...
    'PassbandFrequency', 50, ...        % was 185 before
    'StopbandFrequency', 59, ...
    'PassbandRipple', 0.0001, ...
    'StopbandAttenuation', 65, ...
    'DesignMethod', 'equiripple', ...
    'SampleRate', 6000);
fvtool(LPFilt_50_59)
saveas(gcf, 'S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\LPFilt_50_59.png')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\LPFilt_50_59.mat', 'LPFilt_50_59')


%% Design high-pass filters
HPFilt_385_400 = designfilt('highpassfir', ...
    'PassbandFrequency', 400, ...
    'StopbandFrequency', 385, ...
    'PassbandRipple', 0.0001, ...
    'StopbandAttenuation', 65, ...
    'DesignMethod', 'equiripple', ...
    'SampleRate', 6000);
fvtool(HPFilt_385_400)
saveas(gcf, 'S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\HPFilt_385_400.png')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\HPFilt_385_400.mat', 'HPFilt_385_400')

% Designed for filtering out 300-3000 Hz signal
% According to R. Q. Quiroga's 2015 paper on spike filtering
HPFilt_300_3000 = designfilt('highpassfir', ...
    'PassbandFrequency', 3000, ...
    'StopbandFrequency', 300, ...
    'PassbandRipple', 0.0001, ...
    'StopbandAttenuation', 65, ...
    'DesignMethod', 'equiripple', ...
    'SampleRate', 48000);
fvtool(HPFilt_300_3000)
saveas(gcf, 'S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\HPFilt_300_3000.png')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\HPFilt_300_3000.mat', 'HPFilt_300_3000')



%% Design band-pass filters

% high gamma filter 50Hz - 90Hz
highGammaFilter = designfilt('bandpassfir', ...
                    'StopbandFrequency1', 49, 'PassbandFrequency1', 50, ...
                    'PassbandFrequency2', 90, 'StopbandFrequency2', 91, ...
                    'StopbandAttenuation1', 60, ...
                    'PassbandRipple', 0.001, ...
                    'StopbandAttenuation2', 60, ...
                    'SampleRate', 1000, ...
                    'DesignMethod', 'equiripple');
fvtool(highGammaFilter)
title('High Gamma Filter')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\highGammaFilter.mat', 'highGammaFilter')

load('Filters\highGammaFilter.mat');
fvtool(highGammaFilter)
title('High Gamma Filter')


% low gamma filter 30Hz - 50Hz
lowGammaFilter = designfilt('bandpassfir', ...
                    'StopbandFrequency1', 29, 'PassbandFrequency1', 30, ...
                    'PassbandFrequency2', 50, 'StopbandFrequency2', 51, ...
                    'StopbandAttenuation1', 60, ...
                    'PassbandRipple', 0.001, ...
                    'StopbandAttenuation2', 60, ...
                    'SampleRate', 1000, ...
                    'DesignMethod', 'equiripple');
fvtool(lowGammaFilter)
title('Low Gamma Filter')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\lowGammaFilter.mat', 'lowGammaFilter')

load('Filters\lowGammaFilter.mat');
fvtool(lowGammaFilter)
title('Low Gamma Filter')


% alpha filter 9Hz - 11Hz
alphaFilter = designfilt('bandpassfir', ...
                    'StopbandFrequency1', 8.5, 'PassbandFrequency1', 9, ...
                    'PassbandFrequency2', 11, 'StopbandFrequency2', 11.5, ...
                    'StopbandAttenuation1', 60, ...
                    'PassbandRipple', 0.001, ...
                    'StopbandAttenuation2', 60, ...
                    'SampleRate', 1000, ...
                    'DesignMethod', 'equiripple');
fvtool(alphaFilter)
title('Alpha Filter')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\alphaFilter.mat', 'alphaFilter')

load('Filters\alphaFilter.mat');
fvtool(alphaFilter)
title('Alpha Filter')


% beta filter 13Hz - 30Hz
betaFilter = designfilt('bandpassfir', ...
                    'StopbandFrequency1', 12.5, 'PassbandFrequency1', 13, ...
                    'PassbandFrequency2', 30, 'StopbandFrequency2', 30.5, ...
                    'StopbandAttenuation1', 60, ...
                    'PassbandRipple', 0.001, ...
                    'StopbandAttenuation2', 60, ...
                    'SampleRate', 1000, ...
                    'DesignMethod', 'equiripple');
fvtool(betaFilter)
title('Beta Filter')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\betaFilter.mat', 'betaFilter')

load('Filters\betaFilter.mat');
fvtool(betaFilter)
title('Beta Filter')


% theta filter 4Hz - 8Hz
thetaFilter = designfilt('bandpassfir', ...
                    'StopbandFrequency1', 3.75, 'PassbandFrequency1', 4, ...
                    'PassbandFrequency2', 8, 'StopbandFrequency2', 8.25, ...
                    'StopbandAttenuation1', 60, ...
                    'PassbandRipple', 0.001, ...
                    'StopbandAttenuation2', 60, ...
                    'SampleRate', 1000, ...
                    'DesignMethod', 'equiripple');
fvtool(thetaFilter)
title('Theta Filter')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\thetaFilter.mat', 'thetaFilter')

load('Filters\thetaFilter.mat');
fvtool(thetaFilter)
title('Theta Filter')


% delta filter 1Hz - 4Hz (NOT been run yet)
deltaFilter = designfilt('bandpassfir', ...
                    'StopbandFrequency1', 0.5, 'PassbandFrequency1', 1, ...
                    'PassbandFrequency2', 4, 'StopbandFrequency2', 4.5, ...
                    'StopbandAttenuation1', 60, ...
                    'PassbandRipple', 0.01, ...
                    'StopbandAttenuation2', 60, ...
                    'SampleRate', 1000, ...
                    'DesignMethod', 'equiripple');
fvtool(deltaFilter)
title('Delta Filter')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\deltaFilter.mat', 'deltaFilter')

load('Filters\deltaFilter.mat');
fvtool(deltaFilter)
title('Delta Filter')

% Infra-Slow Oscillation 0.1-1 Hz
% use low-pass filter (1 1.4) instead of bandpass filter
infraSlowFilter = designfilt('lowpassfir', ...
                    'PassbandFrequency', 1, ...
                    'StopbandFrequency', 1.4, ...
                    'PassbandRipple', 0.001, ...
                    'StopbandAttenuation', 60, ...
                    'SampleRate', 1000, ...
                    'DesignMethod', 'equiripple');
fvtool(infraSlowFilter)
title('Infra Slow Filter')
save('S:\Google Drive (edu)\Rutgers University\Research\DBS\Project\Matlab\Code\Filters\infraSlowFilter.mat', 'infraSlowFilter')

load('Filters\infraSlowFilter.mat');
fvtool(infraSlowFilter)
title('Infra Slow Filter')

