function [locs, ampl] = findSpikes(hpfSignal, threshold)
	% MAX_PEAK_WIDTH = 15;
	[ampl, locs] = findpeaks(hpfSignal , ...
						'MinPeakHeight', double(4 * threshold), ...     % set min peak height
						'Annotate', 'peaks');
	% 'MinPeakProminence', double(3.5 * threshold), ...		% vertical drop of more than
	% 'Threshold', double(200), ...  						% greater than adjacent peaks by threshold
	% 'WidthReference', 'halfheight', ...					% halfheight halfprom
	% 'MinPeakWidth', 20, ...
	% 'MaxPeakWidth', MAX_PEAK_WIDTH, ...
	% 'Threshold', 1e-4, ...
	% 'MinPeakWidth', 0.05, ...
	% 'MaxPeakWidth', 4, ...
    
	% [~, a] = size(hpfSignal);
	% binarySpikes = linspace(0, 0, a);
	% binarySpikes(locs) = 1;